### ISSUE TITLE
Provide codelenses for endpoints of the running app

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#114]
connect to local running application
connect to a remote server???
The idea is to provide links from REST endpoints in the code that will be opened in the browser when clicking on them.

Look at how spring tools works with spring boot applications

**Comment by angelozerr** [comment]
Just to clarify this issue, given this REST service :

```java
@Path("/fruits")
public class FruitResource {

    @GET
    public Set<Fruit> list() {}

    @POST
    public Set<Fruit> add(Fruit fruit) {}
```

we want to display the link http://localhost:8080/fruits as codelens before the list() method:

```java
    [http://localhost:8080/fruits]
    @GET
    public Set<Fruit> list() {}

    @POST
    public Set<Fruit> add(Fruit fruit) {}
```

I think we should just manage GET method since POST method could have parameter which cannot be managed with a simple hyperlink (How Spring Boot manage that?)

The challenge here is to 

 * compute the proper URL for list() method.
 * display this hyperlink only when application is started (is it possible?)

I had 3 ideas:
 * JMX
 * Swagger
 * Compute at hand

# JMX

## Spring Boot

Spring Boot can expose the whole Spring beans as JMX when the application starts. For REST service, it expose it as requestMapping MBean. You can see those MBean in the  VisualVM MBeans. Spring Boot LS uses this Spring Boot feature. It create a JMX connection to consume MBeans and retrieve the proper MBean requestMapping which stores the URL.

## Quarkus

In Quarkus application context, it doesn't register MBean for REST services. We could perhaps create our MBean which register REST services but:

 * it will require that pom.xml of the Quarkus application should define our MBean as dependency to execute it when Quarkus application starts.
 * I don't know if it will work since JMX is not supported in Quarkus context. Perhaps it could work on dev mode but not in prod mode when application is build with GraalVM which doesn't support JMX.

# Swagger

Swagger gives the capability to retrieve all REST services from the application and give information about the URL, the signature, etc BUT it doesn't provides the class name, field name where the REST services comes from. In our case I think it's not helpful.

More it requires to declare swagger in the pom.xml.

# Compute at hand

The only way that I see is to compute the URL at hand by JDT LS to get the annotation value (like '/fruits'). About the base url, we could use this strategy:

 * search the value in application.properties 
 * if not defined using localhost:8080 
 * provide a settings in the case of url is managed with other mean like env variable.
