### ISSUE TITLE
Duplicate keys returned in completion

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#15]
- Clone https://github.com/quarkusio/quarkus-quickstarts
- Open https://github.com/quarkusio/quarkus-quickstarts/blob/master/hibernate-orm-resteasy/src/main/resources/application.properties
- autocomplete, there's a duplicate quarkus.datasource key.

<img width="872" alt="Screen Shot 2019-08-02 at 9 09 36 AM" src="https://user-images.githubusercontent.com/148698/62364269-553b2b00-b521-11e9-9598-c3db2e31b7c4.png">

I'm not even sure this is a valid key.

**Comment by angelozerr** [comment]
@fbricon at first please use last version of quarkus ls because with this commit https://github.com/redhat-developer/quarkus-ls/commit/a57f8710d0396d93173e3e18d7185b0cd549a3a2 you will see source of property:

![image](https://user-images.githubusercontent.com/1932211/62411681-4de65100-b5f7-11e9-8ce6-37c395ab408a.png)

I will check if `quarkus.datasource` is correct (I think no, since datasource property is a Map, but let me time to fix that), but the duplicate comes from that there are 2 classes which provides that:

 * AgroalRuntimeConfig
 * AgroalBuildTimeConfig

The question is, do we considere build Quarkus property in application.properties?

**Comment by fbricon** [comment]
Can't reproduce anymore. quarkus.datasource alone is not returned anymore. @angelozerr is it expected? Should we just close it?

**Comment by angelozerr** [comment]
> Can't reproduce anymore. quarkus.datasource alone is not returned anymore. 

Indeed it was wrong. This property was returned because map was not done.

>  @angelozerr is it expected? 

Definitely

> Should we just close it?

Yes please close it. We will reopen it if we found usecases which provides duplicate key.
