### ISSUE TITLE
Missing enum value completion/validation for optional enum

### ISSUE THREAD

**Issue by xorye** [redhat-developer/quarkus-ls#175]
For the following properties: 
```
quarkus.hibernate-search.elasticsearch.automatic-indexing.synchronization-strategy
quarkus.hibernate-search.elasticsearch.backends.{*}.automatic-indexing.synchronization-strategy
quarkus.hibernate-search.elasticsearch.backends.{*}.index-defaults.lifecycle.strategy
quarkus.hibernate-search.elasticsearch.backends.{*}.index-defaults.lifecycle.required-status
quarkus.hibernate-search.elasticsearch.backends.{*}.indexes.{*}.lifecycle.strategy
quarkus.hibernate-search.elasticsearch.backends.{*}.indexes.{*}.lifecycle.required-status
```
each of these properties expect a `java.util.Optional<ENUM VALUE>` as its value. However, when invoking completion for the value, there are no completion options for the enum value.

Also, there is no value validation, meaning that there is no error diagnostic if the value is not a valid enum value.

**Comment by angelozerr** [comment]
@xorye good catch!

I think the problem is in JDT LS extension when we call https://github.com/redhat-developer/quarkus-ls/blob/7c4ae36d82b71ded38a8ef254b56237cb6e74582/microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/AbstractPropertiesProvider.java#L144 The IType is not an enumeration but an optionnal<enum>. 

If you have time to investigate the problem, it should be cool.
