### ISSUE TITLE
Support for `MicroProfile Open API` properties

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#216]
MicroProfile Open API provides some properties that we should supported. See 

https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.adoc#311-core-configurations

**Comment by xorye** [comment]
I have two questions about the OpenAPI properties:

My first question is that for the "prefix" properties:
![image](https://user-images.githubusercontent.com/20326645/76623375-c0ae9780-6509-11ea-8c91-2cb9319d03e9.png)

Since they are just prefixes, I think they should be changed to `mp.openapi.servers.path.{*}`, `mp.openapi.servers.operation.{*}` and `mp.openapi.schema.{*}`. Would that be ok?

My second question is for the `mp.openapi.schema.` property. Supporting this property seems a bit more challenging because its value can spread multiple lines like so:
```
mp.openapi.schema.java.util.Date = { \
  "name": "EpochMillis" \
  "type": "number", \
  "format": "int64", \
  "description": "Milliseconds since January 1, 1970, 00:00:00 GMT" \
}
```
At the moment. if I copy and paste that content into an application.properties file, it looks like this:
![image](https://user-images.githubusercontent.com/20326645/76623553-18e59980-650a-11ea-82aa-0b8325561c62.png)

It seems like the properties parser and the Quarkus Properties textmate grammar should be changed too?

**Comment by angelozerr** [comment]
* mp.openapi.servers.path.{*} : yes you can do that
 * mp.openapi.servers.operation.{*}  : yes you can do that
 * and mp.openapi.schema.{*} : no it will not work since {*} is a feature from Quarkus mapped property. {*}  means that you can have any identifier (without '.'). And if you need '.' you must using qote like quarkus.log."com.redhat.quarkus" (quarkus.log.{*})

Today there are no way to say that a property ends with any character (the case of mp.openapi.schema). Perhaps we should support it with a new syntax like `{here you can fill it with a java regexp}` ?

> It seems like the properties parser and the Quarkus Properties textmate grammar should be changed too?

I'm afraid the answer is yes for both
