### ISSUE TITLE
[qute] parser lenient about new parameters

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#433]
Given this Qute template:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  {#let title="WELCOME" /}
  <title>{title}</title>
</head>
<body>
	{title}
</body>
</html>
```

The current parser doesn't detect any issue, but when running the quarkus app, you see:
<img width="1449" alt="Screenshot 2021-11-24 at 10 26 29" src="https://user-images.githubusercontent.com/148698/143211161-791270c2-74ac-4dca-8f4e-b0520e967070.png">

@mkouba is that really expected from Qute?

**Comment by mkouba** [comment]
> The current parser doesn't detect any issue,

What exactly do you mean by the "current parser"? 

> but when running the quarkus app, you see:

These are validation problems that should be reported when the applicatoin is built and the build should normally fail, e.g. if running `mvn clean package`. In other words, you should see the same errors any time you build your app, not only in the dev mode where a special error page is shown.

Lastly, I think that the template above is wrong because the `{#let}` section is empty and the `title` param is completly ignored, you'll need to "wrap" all `{title}` expressions in the tag, i.e. add `{/let}`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  {#let title="WELCOME"}
  <title>{title}</title>
</head>
<body>
	{title}
</body>
{/let}
</html>
```

**Comment by mkouba** [comment]
Ah sorry, I misread the project ;-). So this is a problem of the language server. Well, in this case the validation errors are caused by the fact that the template is used from a `@CheckedTemplate(requireTypeSafeExpressions = true)` (default value) as defined by https://quarkus.io/guides/qute-reference#typesafe_templates. I'm not sure whether the parser from the `quarkus-ls` can detect this.

**Comment by mkouba** [comment]
FTR _"By default, the templates defined in a class annotated with `@CheckedTemplate` can only contain type-safe expressions, i.e. expressions that can be validated at build time. You can use `@CheckedTemplate(requireTypeSafeExpressions = false)` to relax this requirement."_

**Comment by fbricon** [comment]
current parser == fault tolerant parser used in the IDE. Ideally we should have only one parser for running the app and doing the linting, but ...

Anyways, I'm new to qute so apologies for the badly formed template.
But in any case, we should report the same issues in the IDE and when running the build.

As for requireTypeSafeExpressions, that's currently not supported (see #434 )

**Comment by mkouba** [comment]
> But in any case, we should report the same issues in the IDE and when running the build.

Yes, that might be problematic because the validation is not about syntax but an application context.

**Comment by fbricon** [comment]
@angelozerr so the problem here is the parser ignores the scope of the let block, and considers the title variable as global, after it was defined

**Comment by mkouba** [comment]
> Anyways, I'm new to qute so apologies for the badly formed template.

No problem at all. Feel free to contribute a patch/issue to the docs.

**Comment by mkouba** [comment]
> @angelozerr so the problem here is the parser ignores the scope of the let block, and considers the title variable as global, after it was defined

Not really. From the parser POV the template is legal although the `{title}` would not be `WELCOME` but would result in a `TemplateException` if [strict rendering](https://quarkus.io/guides/qute-reference#strict_rendering) is enabled or `NOT_FOUND` otherwise. The problem is that from the app context we know that the template should be type-safe and all expressions should be validatable which is not the case.
