### ISSUE TITLE
Generate one CodeAction per `TemplateExtensions` class

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/quarkus-ls#677]
We have one code action which generates a new method in an existing `TemplateExtensions`, but we should generate one code action for each existing `TemplateExtensions` that isn't a binary file.

See https://github.com/redhat-developer/quarkus-ls/pull/671#issuecomment-1197058836

**Comment by datho7561** [comment]
This could get fairly complex to support in combination with resolveCodeAction, since we would need to know all the possible `TemplateExtensions` classes before resolving the code action.

**Comment by angelozerr** [comment]
Qute ls know the resolver extension. It means that you  ould remove your code which retrieve templzte extension classes on jdt side and you could loop for thise revolvers to generate code action per resolver

**Comment by angelozerr** [comment]
In this issue we will able to remove the search of existing of template extension https://github.com/redhat-developer/quarkus-ls/blob/8a52980f2a999e80a0367f301f8962dfaf4f84b7/qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/QuteSupportForTemplateGenerateMissingJavaMemberHandler.java#L347 because we will generate a code action per existing template extension class known by the Qute LS.

To collect all Java resolvers class, I suggest that you do like namespaces at https://github.com/redhat-developer/quarkus-ls/blob/8a52980f2a999e80a0367f301f8962dfaf4f84b7/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/ExtendedDataModelProject.java#L70 and my first idea was to have 

`public Set<String> getAllValueResolversClasses() {
`

but it is a bad idea because:

 * it will contains @TemplateExtension classes 
 * but too other classes annotated with @TemplateEnum, etc.

So we need to improve  ValueResolverInfo to store:

 * the kind (TemplateExtension, etc) which can be an enum.
 * the source (Boolean) to know if TemplateExtension is a source or binary.

After that you will able to do like namespace and you could filter with kind and source to have a method like:

`Set<String> getTemplateExtensionSourceTypes();`

like https://github.com/redhat-developer/quarkus-ls/blob/8a52980f2a999e80a0367f301f8962dfaf4f84b7/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/ExtendedDataModelProject.java#L155
