### ISSUE TITLE
NPE when validating Qute template where a method is invoked

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/quarkus-ls#748]
Given the following Qute template, where the object "map" is not declared anywhere:

```qute
{map.get("string")}
```

`map` is marked properly with a warning, however, there is an NPE in the output related to trying to validate `get(...)`

**Comment by angelozerr** [comment]
My PR https://github.com/redhat-developer/quarkus-ls/pull/743 should fix this issue with a test.

**Comment by angelozerr** [comment]
This issue is fixed by https://github.com/redhat-developer/quarkus-ls/pull/743 and it exists a test in https://github.com/redhat-developer/quarkus-ls/blob/ed5e29ae65842e592d6ff8ab278c178b132ae08b/qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java#L731
