### ISSUE TITLE
code assist not returning info due to exception in quarkus-ls

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/quarkus-ls#78]
While working on IntelliJ implementation, I noticed that code assist stopped working after a while.

Please find the log files: one for the LSP messages exchanges and one for the quarkus-ls error output.

[properties_err_20190909.log](https://github.com/redhat-developer/quarkus-ls/files/3589227/properties_err_20190909.log)
[properties_out_20190909.log](https://github.com/redhat-developer/quarkus-ls/files/3589228/properties_out_20190909.log)

**Comment by angelozerr** [comment]
@jeffmaury I tried to replay your scenario with vscode and I suspect that your problem comes from a bug from LSP IJ support about the `rangeLength` when `didChange` is called.

Takes a sample with your trace:

```json
{
  "jsonrpc": "2.0",
  "method": "textDocument/didChange",
  "params": {
    "textDocument": {
      "version": 2,
      "uri": "file:///C:/work/src/tmp/quarkus-test/code-with-quarkus/src/main/resources/application.properties"
    },
    "contentChanges": [
      {
        "range": {
          "start": {
            "line": 2,
            "character": 25
          },
          "end": {
            "line": 2,
            "character": 25
          }
        },
        "rangeLength": 1,
        "text": "j"
      }
    ]
  }
}
```

Here you add the `j` character, without replacing some characters. You should have `rangeLength` equals to 0 (and not to 1)

**Comment by angelozerr** [comment]
I close this issue since the problem comes from IJ LSP client.
